app/main/forms/__init__.py
from app.main.forms.forms import PasswordReset, ProfileUpdate, PhotoUpload

app/main/forms/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField, EmailField, StringField
from wtforms.validators import DataRequired, EqualTo, Length, ValidationError
from flask_wtf.file import FileRequired, FileField, FileSize, FileAllowed
from flask_login import current_user
from app.models import User
from flask import flash

def existing_email(form, field):
        if User.query.filter_by(email=field.data).first() is not None and field.data != current_user.email:
            flash(f"Email: {field.data} is already registered.", category='alert-warning')
            raise ValidationError(f"Email: {field.data} is already registered.")

def existing_username(form, field):
        if User.query.filter_by(username=field.data).first() is not None and field.data != current_user.username:
            flash(f"Username: {field.data} is already registered.", category='alert-warning')
            raise ValidationError(f"Username: {field.data} is already registered.")

class PasswordReset(FlaskForm):
    password = PasswordField('New Password', validators=[DataRequired()])
    confirm_pass = PasswordField('Confirm your password', validators=[EqualTo('password', message='Must match password field'), Length(12,256,message='Password must be atleast 12 characters.')])
    submit = SubmitField('Update Password')

class ProfileUpdate(FlaskForm):
    email = EmailField('Update your email', validators=[existing_email])
    email_confirm = EmailField('Confirm new email', validators=[EqualTo('email')])
    username = StringField('Update your username', validators=[existing_username])
    submit = SubmitField('Update Details')

class PhotoUpload(FlaskForm):
    file = FileField('File', validators=[
        FileAllowed([".jpeg",".png"]),
        FileRequired(message='a file must be included to submit')
    ])
    submit = SubmitField('submit')

app/main/__init__.py
from flask import Blueprint

blp = Blueprint('main', __name__, template_folder='templates/main')

from app.main import views

app/main/views/__init__.py
import app.main.views.views

app/main/views/views.py
from app.main import blp 
from flask import abort, render_template, url_for, redirect, flash, request
from flask_login import current_user, login_required
from app.models import Recipe
from app import db
import os
from config import basedir
from app.main.forms import PasswordReset,ProfileUpdate, PhotoUpload
from app.auth.views.views import role_access


@blp.route('/adminpanel')
@login_required
@role_access(2)
def test_admin():
    return render_template('adminpanel.html')


@blp.route('/')
def index():
    return render_template('index.html')

@blp.route('/myaccount', methods=['GET'])
@login_required
def my_account():
    recipes = Recipe.query.filter_by(created_by=current_user.id).all()
    return render_template('myaccount.html',user=current_user, recipes=recipes)


@blp.route('/updateprofilephoto', methods=["POST"])
def update_profile_photo():
    photo_form = PhotoUpload()
    if photo_form.is_submitted():
        uploaded_file = photo_form.file.data
        if uploaded_file.filename != '':
            sep_file = os.path.splitext(uploaded_file.filename)[1]
            current_user.avatar = str(current_user.id)+sep_file
            uploaded_file.save(basedir+'/app/static/avatars/'+current_user.avatar)
            db.session.add(current_user)
            db.session.commit()
            flash('Profile photo updated.', category='alert-success')
            return redirect(url_for('main.my_account'))
        else:
            raise ValueError('File name not added!')
    else:
        flash('Invalid file upload', category='alert-warning')
        return redirect(url_for('main.update_account'))


@blp.route('/updateprofileinfo', methods=["POST"])
def update_profile_info():
    profile_form = ProfileUpdate()
    email_change = False
    if profile_form.validate_on_submit():
        if current_user.email != profile_form.email.data:
            current_user.email = profile_form.email.data
            current_user.confirmed = False
            email_change = True
        elif current_user.username != profile_form.username.data:
            current_user.username = profile_form.username.data
        db.session.add(current_user)
        db.session.commit()
        flash(('Profile successfully updated.' if not email_change else 'A confirmation email was sent to your new email!'), category='alert-success')
        return redirect(url_for('main.my_account'))
    else:
        flash("Incorrect Password Data", category='alert-warning')
        return redirect(url_for('main.update_account'))

@blp.route('/updatepassword', methods=["POST"])
def update_password():
    pass_form = PasswordReset()
    if pass_form.is_submitted():
        current_user.password = pass_form.password.data
        db.session.add(current_user)
        db.session.commit()
        flash('Password successfully changed.', category='alert-success')
        return redirect(url_for('main.my_account'))
    else:
        flash("Incorrect Password Data", category='alert-warning')
        return redirect(url_for('main.update_account'))

@blp.route('/updateaccount', methods=["GET"])
@login_required
def update_account():
    pass_form = PasswordReset()
    profile_form = ProfileUpdate()
    update_profile_photo = PhotoUpload()
    return render_template('updateaccount.html', pass_form=pass_form,profile_form=profile_form,update_profile_photo=update_profile_photo, user=current_user)

app/main/templates/main/adminpanel.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <h1> This is the admin page for testing</h1>
</div>

{% endblock %}

app/main/templates/main/index.html
{% extends "base.html" %}
{% block content %}

<div class="container jumbotron align-items-center bg-dark my-3">
    <h3 class="text-light" >This is the Home Page </h2>
    <hr class="my-4">
        {% if current_user.is_authenticated %}
        <a href="{{url_for('recipes.add_recipe')}}" class="btn btn-secondary-outline my-4 bg-light"> Add Recipes <i class="fa fa-arrow-right"></i></a>
        {% else %}
        <a href="{{url_for('auth.login')}}" class="btn btn-secondary-outline  bg-light my-4"> Login <i class="fa fa-arrow-right"></i></a>
        {% endif %}
    </p>
</div>
<div class="container align-items-center">
    <p>
            Hello, 
            {% if current_user.is_authenticated %}
            {{current_user.username | capitalize }}
            {% else %}
            Stranger
            {% endif %}! <br>
            Please use any of the links above for navigation.
    </p>
</div>

<style>
    #jumborecipe{
        background-image: url("https://media.istockphoto.com/id/1363638825/photo/vegan-plant-based-asian-food-recipes-with-rice-and-brown-rice-as.jpg?s=1024x1024&w=is&k=20&c=qTpZMJEEmuaEFZBULfj3gk4NDCkKoECh2b1T12DOnj8=");
    }
</style>
{% endblock %}

app/main/templates/main/myaccount.html
{% extends "base.html" %}
{% block content %}
<div class="container jumbotron bg-secondary text-white my-3"> <h3>Account Page</h3></div>
<div class="container">
    <div class="row">
        <div class="col-4 rounded">
            <img src="{{url_for('static', filename='avatars/'+current_user.avatar)}}" width="200" height="200" alt="profile_photo">
        </div>

        <div class="col-4">
            Username: {{user.username}} <br>
            Recipes Created: {{recipes | count}} <br>
            Email: {{user.email}} <br>
            Last Seen: {{user.last_seen.strftime('%B %d, %Y')}} <br>
            Member Since: {{user.member_since.strftime('%B %d, %Y')}} <br>
        </div>
    </div>
    <hr class="mb-5 mt-4">
    <div class="container d-flex flex-wrap align-items-center">
        {% for recipe in recipes %}
        <div class="card m-3 bg-dark text-white" style="width: 18rem;">
            <img class="card-img-top" src="{{url_for('recipes.static', filename=recipe.image)}}" alt="Card image cap" width="200" height="150">
            <div class="card-body">
              <em class="card-title">{{recipe.name}}</em>
              {% if recipe.description == '' %}
              <p class="card-text">Delicous, why don't we add a description?</p>
              {% else %}
              <p class="card-text">{{recipe.description | truncate(64, killwords=True ,end='...')}}</p>
              {% endif %}
              <div class="container text-center">
                <a href="{{url_for('recipes.recipe_view', recipe_id=recipe.id)}}" class="btn btn-secondary">Try it!</a>
              </div>
            </div>
          </div>
        {% endfor %}
    </div>
</div>





{%endblock%}

app/main/templates/main/updateaccount.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="jumbotron bg-dark text-white align-text-center my-3"> 
        <h3> Profile Update Page </h3>
    </div>
    <div class="container" id="profile_form">
        <div class="row">
            <div class="col4 border-right">
                <img src="../../../static/avatars/{{user.avatar}}" width="200" height="200" alt="profile_photo">
                <form method="POST" enctype="multipart/form-data" action="{{url_for('main.update_profile_photo')}}">
                    {{update_profile_photo.hidden_tag()}}
                    {{update_profile_photo.file(class_="form-control")}}
                    {{update_profile_photo.submit(class_="form-control btn btn-secondary my-2 px-4")}}
                </form>
            </div>
            <div class="col-2">
                <!-- Empty Spacing for Future columns-->
            </div>
            <div class="col-4">
                <form method="POST" id="update_profile_info" action="{{url_for('main.update_profile_info')}}">
                    {{profile_form.hidden_tag()}}
                    <div class="px-3 mx-3">
                        {{profile_form.username.label}}
                        {{profile_form.username(class_="form-control",value=current_user.username)}}
            
                        {{profile_form.email.label}}
                        {{profile_form.email(class_="form-control",value=current_user.email)}}
                        {{profile_form.email_confirm.label}}
                        {{profile_form.email_confirm(class_="form-control",value=current_user.email)}}
                        {{profile_form.submit(class_="form-control btn btn-secondary my-2")}}
                    </div>
                </form>
            </div>
        </div>
  
    </div>
    <hr class="my-5">
    <div class="container" id="pass_form">
        <form method="POST"  action="{{url_for('main.update_password')}}">
            {{pass_form.hidden_tag()}}
            <div class="px-5 mx-5">
                {{pass_form.password.label}}
                {{pass_form.password(class_="form-control")}}
    
                {{pass_form.password.label}}
                {{pass_form.password(class_="form-control")}}
                {{pass_form.submit(class_="form-control btn btn-secondary my-2")}}
            </div>
        </form>
    </div>

</div>



{% endblock %}